CREATE TABLE MCU_NEW (
    NOPENDAFTARAN char(17) PRIMARY KEY,
    USER_ENTRY VARCHAR(25),
    TGLJAM_ENTRY DATETIME,

    TD VARCHAR(25),
    NADI VARCHAR(25),
    SUHU VARCHAR(25),
    SP02 VARCHAR(25),
    RR VARCHAR(25),
    TB VARCHAR(25),
    BB VARCHAR(25),
    IMT VARCHAR(25),

    KELUHAN VARCHAR(200),
    PEMERIKSAANFISIK VARCHAR(200),
    DIAGNOSIS VARCHAR(200),
    PENUNJANG VARCHAR(50),
    RENCANATERAPI VARCHAR(200),

    KESIMPULAN VARCHAR(50),

    DRPEMERIKSA VARCHAR(100),
    NOPEMERIKSA CHAR(2)    
    
);