<div class="card-body">
    {{-- Hidden fields for URLs and data --}}
    <input type="hidden" id="moews-nopendaftaran" value="{{ $noPendaftaran }}">
    <input type="hidden" id="moews-norm" value="{{ $norm }}">
    <input type="hidden" id="moews-user" value="{{ trim($user['username']) }}">
    <input type="hidden" id="moews-url-history" value="{{ route('rme.igd.form.moews.history') }}">
    <input type="hidden" id="moews-url-store" value="{{ route('rme.igd.form.moews.store') }}">
    <input type="hidden" id="moews-url-destroy" value="{{ route('rme.igd.form.moews.destroy') }}">

    <div class="card card-outline card-primary shadow-sm">
        <div class="card-header">
            <h3 class="card-title mt-1">Modified Obstetric Early Warning System (MOEWS)</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-success btn-sm" id="btnAddAssessmentMoews">
                    <i class="fas fa-plus-circle mr-1"></i>Tambah Pemeriksaan
                </button>
                <button type="button" class="btn btn-primary btn-sm" id="btnSaveAllMoews">
                    <i class="fas fa-save mr-1"></i>Simpan Semua
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive" id="moews-table-container">
                <table class="table table-bordered table-hover" id="moewsTable" style="min-width: 1000px;">
                    <thead class="thead-light text-center align-middle">
                        {{-- Header will be generated by JS --}}
                    </thead>
                    <tbody id="moewsTableBody">
                        <tr>
                            <td colspan="10" class="text-center p-5">
                                <i class="fas fa-spinner fa-spin fa-2x"></i>
                                <p class="mt-2">Memuat data...</p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="alert alert-info mt-3">
                <h5 class="alert-heading"><i class="fas fa-info-circle"></i> Petunjuk Skor:</h5>
                <ul class="mb-0 pl-4">
                    <li><strong>0-2 (TTV/8 JAM):</strong> Observasi dan Dokumentasi</li>
                    <li><strong>3-4 (TTV/4 JAM):</strong> Observasi dan Dokumentasi, jika perlu lapor dokter</li>
                    <li><strong>5-6 (TTV/JAM):</strong> Observasi Bedside Monitor bersama dokter, persiapan Ruang Intensif</li>
                    <li><strong>≥7 (BEDSIDE):</strong> Observasi Bedside Monitor bersama dokter, persiapan Ruang Intensif dan Ventilator</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<style>
    #moewsTable th, #moewsTable td {
        vertical-align: middle;
    }
    #moewsTable .sticky-col {
        position: sticky;
        left: 0;
        z-index: 2;
        background-color: #fff;
    }
    #moewsTable thead .sticky-col {
        z-index: 3;
    }
    .param-group {
        background-color: #f8f9fa;
        font-weight: bold;
    }
    .btn-outline-secondary.score-0.active { background-color: #28a745 !important; border-color: #28a745 !important; color: white !important; }
    .btn-outline-secondary.score-1.active { background-color: #ffc107 !important; border-color: #ffc107 !important; color: black !important; }
    .btn-outline-secondary.score-2.active { background-color: #fd7e14 !important; border-color: #fd7e14 !important; color: white !important; }
    .btn-outline-secondary.score-3.active { background-color: #dc3545 !important; border-color: #dc3545 !important; color: white !important; }

    .total-score-cell {
        font-weight: bold;
        font-size: 1.2rem;
    }
</style>

<script>
$(document).ready(function() {
    // --- CONFIG & GLOBAL VARS ---
    const config = {
        noPendaftaran: $('#moews-nopendaftaran').val(),
        norm: $('#moews-norm').val(),
        currentUser: $('#moews-user').val(),
        urls: {
            history: $('#moews-url-history').val(),
            store: $('#moews-url-store').val(),
            destroy: $('#moews-url-destroy').val(),
        }
    };

    const parameters = [
        { group: 'Tanggal Pemeriksaan', name: 'TGL', type: 'date' },
        { group: 'Jam Pemeriksaan', name: 'JAM', type: 'time' },
        { group: 'Frekuensi Nafas', options: [
            { label: '≥ 25', name: 'FREKUENSI_NAFAS_25', score: 3, color: 'score-3' },
            { label: '21-25', name: 'FREKUENSI_NAFAS_21', score: 2, color: 'score-2' },
            { label: '12-20', name: 'FREKUENSI_NAFAS_20', score: 0, color: 'score-0' },
            { label: '≤ 12', name: 'FREKUENSI_NAFAS_12', score: 3, color: 'score-3' },
        ]},
        { group: 'Saturasi Oksigen (%)', options: [
            { label: '≥ 95%', name: 'SATURASI_OKSIGEN_95', score: 0, color: 'score-0' },
            { label: '92-95%', name: 'SATURASI_OKSIGEN_92', score: 1, color: 'score-1' },
            { label: '≤ 92%', name: 'SATURASI_OKSIGEN_90', score: 3, color: 'score-3' },
        ]},
        { group: 'Oksigen', options: [
            { label: 'Ya', name: 'OKSIGEN_YA', score: 2, color: 'score-2' },
            { label: 'Tidak', name: 'OKSIGEN_TIDAK', score: 0, color: 'score-0' },
        ]},
        { group: 'Suhu (°C)', options: [
            { label: '≥ 37,7', name: 'SUHU_37', score: 3, color: 'score-3' },
            { label: '36,5-37,7', name: 'SUHU_36', score: 1, color: 'score-1' },
            { label: '36,1-37,5', name: 'SUHU_35', score: 0, color: 'score-0' },
            { label: '≤ 36', name: 'SUHU_30', score: 3, color: 'score-3' },
        ]},
        { group: 'TD Sistolik (mmHg)', options: [
            { label: '≥ 160', name: 'TD_SISTOLIK_160', score: 3, color: 'score-3' },
            { label: '151-160', name: 'TD_SISTOLIK_151', score: 2, color: 'score-2' },
            { label: '141-150', name: 'TD_SISTOLIK_141', score: 1, color: 'score-1' },
            { label: '131-140', name: 'TD_SISTOLIK_131', score: 0, color: 'score-0' },
            { label: '121-130', name: 'TD_SISTOLIK_121', score: 0, color: 'score-0' },
            { label: '111-120', name: 'TD_SISTOLIK_111', score: 0, color: 'score-0' },
            { label: '101-110', name: 'TD_SISTOLIK_101', score: 0, color: 'score-0' },
            { label: '91-100', name: 'TD_SISTOLIK_91', score: 0, color: 'score-0' },
            { label: '≤ 90', name: 'TD_SISTOLIK_90', score: 3, color: 'score-3' },
        ]},
        { group: 'TD Diastolik (mmHg)', options: [
            { label: '≥ 111', name: 'TD_DIASTOLIK_111', score: 3, color: 'score-3' },
            { label: '101-110', name: 'TD_DIASTOLIK_101', score: 1, color: 'score-1' },
            { label: '91-100', name: 'TD_DIASTOLIK_91', score: 0, color: 'score-0' },
            { label: '61-90', name: 'TD_DIASTOLIK_61', score: 1, color: 'score-1' },
            { label: '≤ 60', name: 'TD_DIASTOLIK_60', score: 3, color: 'score-3' },
        ]},
        { group: 'Nadi (x/menit)', options: [
            { label: '≥ 121', name: 'NADI_121', score: 3, color: 'score-3' },
            { label: '111-120', name: 'NADI_111', score: 1, color: 'score-1' },
            { label: '101-110', name: 'NADI_101', score: 1, color: 'score-1' },
            { label: '61-100', name: 'NADI_61', score: 0, color: 'score-0' },
            { label: '50-60', name: 'NADI_50', score: 2, color: 'score-2' },
            { label: '≤ 50', name: 'NADI_40', score: 3, color: 'score-3' },
        ]},
        { group: 'Kesadaran', options: [
            { label: 'Alert (A)', name: 'KESADARAN_A', score: 0, color: 'score-0' },
            { label: 'Voice/Pain/Unresponsive (VPU)', name: 'KESADARAN_VPU', score: 3, color: 'score-3' },
        ]},
        { group: 'Nyeri', options: [
            { label: 'Normal', name: 'NYERI_NORMAL', score: 0, color: 'score-0' },
            { label: 'Abnormal', name: 'NYERI_ABNORMAL', score: 3, color: 'score-3' },
        ]},
        { group: 'Discharge/Lochia', options: [
            { label: 'Normal', name: 'DISCHARGE_NORMAL', score: 0, color: 'score-0' },
            { label: 'Abnormal', name: 'DISCHARGE_ABNORMAL', score: 3, color: 'score-3' },
        ]},
        { group: 'Proteinuria', options: [
            { label: 'Negatif', name: 'PROTEINURIA_NEGATIF', score: 0, color: 'score-0' },
            { label: '+', name: 'PROTEINURIA_POSITIF', score: 2, color: 'score-2' },
            { label: '++/+++', name: 'PROTEINURIA_POSITIF2', score: 3, color: 'score-3' },
        ]},
        { group: 'Kondisi Lain', options: [
            { label: 'Postpartum Hemorhagi/Risiko Tinggi Kardiovaskular', name: 'POSTPARTUM', score: 3, color: 'score-3' },
            { label: 'Keluhan Pre-Eklampsia', name: 'PREEKLAMPSIA', score: 0, color: 'score-0' },
        ]},
        { group: 'Total Skor', name: 'TOTAL_SKOR', type: 'total' },
        { group: 'Nama Petugas PPA', name: 'NAMA_PPA', type: 'text' },
        { group: 'Kesimpulan', name: 'KESIMPULAN', type: 'conclusion' }, // This will be handled by logic
        { group: 'Kondisi Khusus', options: [
            { label: 'Henti Jantung', name: 'HENTI_JANTUNG', score: 0, color: 'score-3' }, // Score is not added, but it's a critical flag
        ]},
    ];

    let assessments = [];

    // --- UI FUNCTIONS ---
    function renderTable() {
        const thead = $('#moewsTable thead');
        const tbody = $('#moewsTableBody');
        thead.empty();
        tbody.empty();

        // Render Header
        let headerHtml = '<tr><th class="sticky-col" style="width: 250px;">Parameter</th>';
        if (assessments.length === 0) {
            headerHtml += '<th class="text-center">Pemeriksaan 1</th>';
        } else {
            assessments.forEach((ass, index) => {
                headerHtml += `<th class="text-center">Pemeriksaan ${index + 1} <button class="btn btn-xs btn-danger btn-remove-assessment" data-counter="${ass.COUNTER}" title="Hapus Pemeriksaan"><i class="fas fa-trash-alt"></i></button></th>`;
            });
        }
        headerHtml += '</tr>';
        thead.html(headerHtml);

        // Render Body
        parameters.forEach(param => {
            let rowHtml = `<tr><td class="sticky-col ${param.options ? '' : 'font-weight-bold'}">${param.group}</td>`;

            const renderCell = (assessment, index) => {
                const counter = assessment ? assessment.COUNTER : 'new_0';
                let cellContent = '';

                if (param.type === 'date') {
                    const val = assessment ? (assessment.TGL || '') : moment().format('YYYY-MM-DD');
                    cellContent = `<input type="date" class="form-control form-control-sm" data-counter="${counter}" data-name="TGL" value="${val}">`;
                } else if (param.type === 'time') {
                    const val = assessment ? (assessment.JAM || '') : moment().format('HH:mm');
                    cellContent = `<input type="time" class="form-control form-control-sm" data-counter="${counter}" data-name="JAM" value="${val}">`;
                } else if (param.type === 'text') {
                    const val = assessment ? (assessment.NAMA_PPA || config.currentUser) : config.currentUser;
                    cellContent = `<input type="text" class="form-control form-control-sm" data-counter="${counter}" data-name="NAMA_PPA" value="${val}">`;
                } else if (param.type === 'total') {
                    const val = assessment ? (assessment.TOTAL_SKOR || 0) : 0;
                    cellContent = `<div class="total-score-cell text-center" data-counter="${counter}" data-name="TOTAL_SKOR">${val}</div>`;
                } else if (param.type === 'conclusion') {
                    cellContent = `<div class="conclusion-cell text-center font-weight-bold" data-counter="${counter}" data-name="KESIMPULAN">-</div>`;
                } else if (param.options) {
                    cellContent = '<div class="btn-group-vertical btn-group-toggle w-100" data-toggle="buttons">';
                    param.options.forEach(opt => {
                        const isChecked = assessment ? (assessment[opt.name] == 1) : false;
                        const activeClass = isChecked ? 'active' : '';
                        const colorClass = opt.color || `score-${opt.score}`; // Ensure color class is always present
                        cellContent += `
                            <label class="btn btn-outline-secondary btn-sm ${activeClass} ${colorClass}">
                                <input type="radio" name="radio_${param.group.replace(/\s/g, '')}_${counter}" class="moews-radio"
                                       data-counter="${counter}" data-name="${opt.name}" data-score="${opt.score}" ${isChecked ? 'checked' : ''}>
                                ${opt.label}
                            </label>`;
                    });
                    cellContent += '</div>';
                }
                return `<td>${cellContent}</td>`;
            };

            if (assessments.length === 0) {
                rowHtml += renderCell(null, 0);
            } else {
                assessments.forEach((ass, index) => {
                    rowHtml += renderCell(ass, index);
                });
            }
            rowHtml += '</tr>';
            tbody.append(rowHtml);
        });

        // Recalculate all scores and conclusions after rendering
        if (assessments.length === 0) {
            calculateScore('new_0');
        } else {
            assessments.forEach(ass => calculateScore(ass.COUNTER));
        }
    }

    function calculateScore(counter) {
        let totalScore = 0;
        $(`.moews-radio[data-counter="${counter}"]:checked`).each(function() {
            totalScore += parseInt($(this).data('score'));
        });

        // Update total score display
        const totalCell = $(`.total-score-cell[data-counter="${counter}"]`);
        totalCell.text(totalScore);

        // Update conclusion display
        const conclusionCell = $(`.conclusion-cell[data-counter="${counter}"]`);
        let conclusionText = '-';
        let conclusionClass = '';
        if (totalScore >= 7) {
            conclusionText = '≥7';
            conclusionClass = 'score-3';
        } else if (totalScore >= 5) {
            conclusionText = '5-6';
            conclusionClass = 'score-2';
        } else if (totalScore >= 3) {
            conclusionText = '3-4';
            conclusionClass = 'score-1';
        } else {
            conclusionText = '0-2';
            conclusionClass = 'score-0';
        }
        conclusionCell.text(conclusionText).removeClass('score-0 score-1 score-2 score-3').addClass(conclusionClass);

        // Handle Pre-Eklampsia alert
        if ($(`.moews-radio[data-name="PREEKLAMPSIA"][data-counter="${counter}"]`).is(':checked')) {
             Swal.fire({
                toast: true, position: 'top-end',
                icon: 'warning', title: 'Perhatian! Segera hubungi DPJP untuk pasien dengan keluhan Pre-Eklampsia.',
                showConfirmButton: false, timer: 5000
            });
        }
    }

    // --- DATA HANDLING ---
    function loadHistory() {
        $.get(config.urls.history, { nopendaftaran: config.noPendaftaran }, function(response) {
            if (response.status === 'success') {
                assessments = response.data;
                if (assessments.length === 0) {
                    addAssessment(); // Add one new column if no history
                } else {
                    renderTable();
                }
            } else {
                Swal.fire('Error', 'Gagal memuat riwayat MOEWS.', 'error');
                addAssessment();
            }
        }).fail(() => {
            Swal.fire('Error', 'Gagal menghubungi server untuk memuat riwayat.', 'error');
            addAssessment();
        });
    }

    function addAssessment() {
        const newCounter = assessments.length > 0 ? Math.max(...assessments.map(a => a.COUNTER)) + 1 : 1;
        const newAssessment = { COUNTER: newCounter, isNew: true };
        
        // Set default values for new assessment
        parameters.forEach(param => {
            if (param.name === 'TGL') {
                newAssessment[param.name] = moment().format('YYYY-MM-DD');
            } else if (param.name === 'JAM') {
                newAssessment[param.name] = moment().format('HH:mm');
            } else if (param.name === 'NAMA_PPA') {
                newAssessment[param.name] = config.currentUser;
            }
            if (param.options) {
                param.options.forEach(opt => newAssessment[opt.name] = 0);
            }
        });
        assessments.push(newAssessment);
        renderTable();
    }

    function saveAll() {
        const assessmentsToSave = [];
        const counters = assessments.map(a => a.COUNTER);

        counters.forEach(counter => {
            const assessmentData = { COUNTER: counter };
            $(`[data-counter="${counter}"]`).each(function() {
                const el = $(this);
                const name = el.data('name');
                if (el.is('input[type="date"], input[type="time"], input[type="text"]')) {
                    assessmentData[name] = el.val();
                }
            });

            // Collect checkbox data
            $(`.moews-radio[data-counter="${counter}"]`).each(function() {
                const el = $(this);
                assessmentData[el.data('name')] = el.is(':checked') ? 1 : 0;
            });

            assessmentsToSave.push(assessmentData);
        });

        const button = $('#btnSaveAllMoews');
        button.prop('disabled', true).html('<i class="fas fa-spinner fa-spin mr-1"></i>Menyimpan...');

        $.ajax({
            url: config.urls.store,
            type: 'POST',
            data: {
                _token: "{{ csrf_token() }}",
                nopendaftaran: config.noPendaftaran,
                norm: config.norm,
                assessments: assessmentsToSave // This should be correct
            },
            success: function(response) {
                if (response.status === 'success') {
                    Swal.fire('Berhasil', response.message, 'success').then(() => {
                        loadHistory();
                    });
                } else {
                    Swal.fire('Gagal', response.message || 'Terjadi kesalahan saat menyimpan.', 'error');
                }
            },
            // Blok 'error' dihapus agar penanganan error global di rme/igd/index.blade.php (ajaxError)
            // dapat menangani kasus sesi habis (401) dan error server lainnya secara konsisten.
            complete: function() {
                button.prop('disabled', false).html('<i class="fas fa-save mr-1"></i>Simpan Semua');
            }
        });
    }

    function removeAssessment(counter) {
        const assessment = assessments.find(a => a.COUNTER == counter);

        Swal.fire({
            title: 'Hapus Pemeriksaan Ini?',
            text: "Tindakan ini tidak dapat dibatalkan.",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Ya, Hapus!',
            cancelButtonText: 'Batal'
        }).then((result) => {
            if (result.isConfirmed) {
                if (assessment && assessment.isNew) {
                    // Just remove from local array if it's a new, unsaved column
                    assessments = assessments.filter(a => a.COUNTER != counter);
                    renderTable();
                    Swal.fire('Dibatalkan', 'Pemeriksaan baru telah dibatalkan.', 'info');
                } else {
                    // Send delete request to server for existing data
                    $.ajax({
                        url: config.urls.destroy,
                        type: 'POST',
                        data: {
                            _token: "{{ csrf_token() }}",
                            nopendaftaran: config.noPendaftaran,
                            counter: counter
                        },
                        success: function(response) {
                            if (response.status === 'success') {
                                Swal.fire('Terhapus!', response.message, 'success').then(() => {
                                    loadHistory();
                                });
                            } else {
                                Swal.fire('Gagal', response.message, 'error');
                            }
                        },
                        error: function(xhr) {
                            Swal.fire('Error', xhr.responseJSON?.message || 'Gagal menghubungi server.', 'error');
                        }
                    });
                }
            }
        });
    }

    // --- EVENT LISTENERS ---
    $('#btnAddAssessmentMoews').click(addAssessment);
    $('#btnSaveAllMoews').click(saveAll);

    // --- Logika untuk membatalkan pilihan (unchecking radio buttons) ---
    // Memungkinkan pengguna untuk mengklik tombol yang aktif untuk membatalkan pilihannya.
    $(document).on('click', '.btn-group-toggle .btn', function(e) {
        const $label = $(this);
        const $radio = $label.find('.moews-radio');

        // Jika radio sudah terpilih SEBELUM event click ini mengubahnya,
        // maka kita ingin membatalkan pilihan tersebut.
        if ($label.hasClass('active')) {
            // Mencegah event default (yang akan memilih radio lain)
            e.preventDefault();
            // Hapus status aktif dan batalkan centang, lalu picu 'change' untuk kalkulasi ulang.
            $label.removeClass('active');
            $radio.prop('checked', false).trigger('change');
        }
        // Jika tidak aktif, biarkan perilaku default Bootstrap berjalan (memilih radio).
    });

    $(document).on('change', '.moews-radio', function() {
        const counter = $(this).data('counter');
        calculateScore(counter);
    });

    $(document).on('click', '.btn-remove-assessment', function() {
        const counter = $(this).data('counter');
        removeAssessment(counter);
    });

    // --- INITIAL LOAD ---
    loadHistory();
});
</script>