CREATE TABLE IDENTIFIKASIBAYILAHIR (
    NOPENDAFTARAN char(17) PRIMARY KEY,
    USER_ENTRY VARCHAR(25),
    TGLJAM_ENTRY DATETIME,

    NM_IBU VARCHAR(100),
    NM_AYAH VARCHAR(100),
    NM_BAYI VARCHAR(100),
    DOKTERBIDAN_PENOLONG VARCHAR(100),

    TGLLAHIR_BAYI DATETIME,
    JAMLAHIR CHAR(8),
    JENKEL CHAR(1),
    TTD IMAGE,
    WARNAKULIT VARCHAR(25),
    BB VARCHAR(25),
    PANJANG VARCHAR(25),

    CAPJARI_IBU IMAGE,
    CAP5JARIKAKIKIRI_BAYI IMAGE,
    CAP5JARIKAKIKANAN_BAYI IMAGE,
    
    TTD_KELUARGA IMAGE,      
    
);