CREATE TABLE LUKAREEDA (
    NOPENDAFTARAN char(17) PRIMARY KEY,
    USER_ENTRY VARCHAR(25),
    TGLJAM_ENTRY DATETIME,

    JENISLUKA VARCHAR(50),
    UNIT VARCHAR(50),

    R_TDKMERAH0 BIT,
    R_MERAH1 BIT,
    R_MERAH2 BIT,
    R_MERAH3 BIT,

    E_TDKEDEMA0 BIT,
    E_RINGAN1 BIT,
    E_SEDANG2 BIT,
    E_BERAT3 BIT,

    E_TDKMEMAR0 BIT,
    E_MEMAR1 BIT,
    E_MEMAR2 BIT,
    E_MEMAR3 BIT,

    D_TDKCAIRAN0 BIT,
    D_SEROSASDKT1 BIT,
    D_SERSDG2 BIT,
    D_PURULEN3 BIT,

    A_LUKAMENYATU0 BIT,
    A_TERBUKA1 BIT,
    A_TERBUKA2 BIT,
    A_TERBUKA3 BIT,

    TOTALSKOR VARCHAR(10),

    CATATANKLINIS VARCHAR(200),
    RTL_OBSERVASIULG BIT,
    RTL_KONSULDR BIT,
    RTL_KULTURLUKA BIT,
    RTL_PRWTNKHUSUS BIT,
    RTL_LAIN BIT,
    RTLLAIN_KET VARCHAR(100)   
    
);