<div class="card-body">
    {{-- Hidden fields for URLs and data --}}
    <input type="hidden" id="pews-nopendaftaran" value="{{ $noPendaftaran }}">
    <input type="hidden" id="pews-norm" value="{{ $norm }}">
    <input type="hidden" id="pews-user" value="{{ trim($user['username']) }}">
    <input type="hidden" id="pews-url-history" value="{{ route('rme.igd.form.pews.history') }}">
    <input type="hidden" id="pews-url-store" value="{{ route('rme.igd.form.pews.store') }}">
    <input type="hidden" id="pews-url-destroy" value="{{ route('rme.igd.form.pews.destroy') }}">

    <div class="card card-outline card-primary shadow-sm">
        <div class="card-header">
            <h3 class="card-title mt-1">Pediatric Early Warning System (PEWS)</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-success btn-sm" id="btnAddAssessmentPews">
                    <i class="fas fa-plus-circle mr-1"></i>Tambah Pemeriksaan
                </button>
                <button type="button" class="btn btn-primary btn-sm" id="btnSaveAllPews">
                    <i class="fas fa-save mr-1"></i>Simpan Semua
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive" id="pews-table-container">
                <table class="table table-bordered table-hover" id="pewsTable" style="min-width: 1000px;">
                    <thead class="thead-light text-center align-middle">
                        {{-- Header will be generated by JS --}}
                    </thead>
                    <tbody id="pewsTableBody">
                        <tr>
                            <td colspan="10" class="text-center p-5">
                                <i class="fas fa-spinner fa-spin fa-2x"></i>
                                <p class="mt-2">Memuat data...</p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="alert alert-info mt-3">
                <h5 class="alert-heading"><i class="fas fa-info-circle"></i> Petunjuk Skor:</h5>
                <ul class="mb-0 pl-4">
                    <li><strong>0-2 (TTV/8 JAM):</strong> Observasi dan Dokumentasi</li>
                    <li><strong>3-4 (TTV/4 JAM):</strong> Observasi dan Dokumentasi, jika perlu lapor dokter</li>
                    <li><strong>5-6 (TTV/JAM):</strong> Observasi Bedside Monitor bersama dokter, persiapan Ruang Intensif</li>
                    <li><strong>≥7 (BEDSIDE):</strong> Observasi Bedside Monitor bersama dokter, persiapan Ruang Intensif dan Ventilator</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<style>
    #pewsTable th, #pewsTable td {
        vertical-align: middle;
    }
    #pewsTable .sticky-col {
        position: sticky;
        left: 0;
        z-index: 2;
        background-color: #fff;
    }
    #pewsTable thead .sticky-col {
        z-index: 3;
    }
    .param-group {
        background-color: #f8f9fa;
        font-weight: bold;
    }
    .btn-outline-secondary.score-0.active { background-color: #28a745 !important; border-color: #28a745 !important; color: white !important; }
    .btn-outline-secondary.score-1.active { background-color: #ffc107 !important; border-color: #ffc107 !important; color: black !important; }
    .btn-outline-secondary.score-2.active { background-color: #fd7e14 !important; border-color: #fd7e14 !important; color: white !important; }
    .btn-outline-secondary.score-3.active { background-color: #dc3545 !important; border-color: #dc3545 !important; color: white !important; }

    .total-score-cell {
        font-weight: bold;
        font-size: 1.2rem;
    }
</style>

<script>
$(document).ready(function() {
    // --- CONFIG & GLOBAL VARS ---
    const config = {
        noPendaftaran: $('#pews-nopendaftaran').val(),
        norm: $('#pews-norm').val(),
        currentUser: $('#pews-user').val(),
        urls: {
            history: $('#pews-url-history').val(),
            store: $('#pews-url-store').val(),
            destroy: $('#pews-url-destroy').val(),
        }
    };

    // Log URLs to console for debugging
    console.log('PEWS Config:', config);
    console.log('PEWS Store URL:', config.urls.store);
    console.log('PEWS History URL:', config.urls.history);
    const parameters = [
        { group: 'Tanggal Pemeriksaan', name: 'TGL', type: 'date' },
        { group: 'Jam Pemeriksaan', name: 'JAM', type: 'time' },
        { group: 'Parameter Perilaku', options: [
            { label: 'Bermain', name: 'PERILAKU_BERMAIN', score: 0, color: 'score-0' },
            { label: 'Tidur', name: 'PERILAKU_TIDUR', score: 1, color: 'score-1' },
            { label: 'Iritabel', name: 'PERILAKU_IRITABEL', score: 2, color: 'score-2' }, // Corrected typo
            { label: 'Letargi <br>Bingung <br>Respon Nyeri Berkurang', name: 'PERILAKU_LETARGI', score: 3, color: 'score-3' }, // Corrected typo
        ]},
        { group: 'Parameter Cardiovasculer', options: [
            { label: 'Pink <br> pink CRT <2 detik', name: 'CARDIO_PINK', score: 0, color: 'score-0' },
            { label: 'Pucat <br>CRT 3 detik', name: 'CARDIO_PUCAT', score: 1, color: 'score-1' },
            { label: 'Pucat <br> CRT 4 detik <br>Nadi 120x/menit <br>Diaforesis', name: 'CARDIO_PUCAT2', score: 2, color: 'score-2' },
            { label: 'Abu - abu dengan Bintik <br>CRT > 5 detik <br> Nadi > 150x/menit', name: 'CARDIO_ABU', score: 3, color: 'score-3' },
        ]},
        { group: 'Parameter Pernapasan', options: [
            { label: 'Normal', name: 'PERILAKU_NORMAL', score: 0, color: 'score-0' },
            { label: 'RR > 24 x/menit <br>Otot bantu nafas (+) <br>FiO2 30% <br>Oksigen 3 Lpm (Nasal Kanul)', name: 'PERILAKU_RR24', score: 1, color: 'score-1' },
            { label: 'RR < 30 x/menit <br>Retraksi dada <br>Oksigen 6 Lpm (NRM)', name: 'PERILAKU_RR30', score: 2, color: 'score-2' },
            { label: 'RR < 20 x/menit <br>Retraksi dada <br>Merintih <br>FiO2 50% <br> Oksigen 8 Lpm (NRM)', name: 'PERILAKU_RR20', score: 3, color: 'score-3' },
        ]},
        { group: 'Kondisi Lain', options: [
            { label: 'Nebulisasi per 6 jam', name: 'NEBULISASI', score: 2, color: 'score-2' },
            { label: 'Muntah persisten setelah operasi', name: 'MUNTAH', score: 2, color: 'score-2' },
        ]},
        { group: 'Total Skor', name: 'TOTAL_SKOR', type: 'total' },
        { group: 'Nama Petugas PPA', name: 'NAMA_PPA', type: 'text' },
        { group: 'Kesimpulan', name: 'KESIMPULAN', type: 'conclusion' },
        { group: 'Kondisi Khusus', options: [
            { label: 'Henti Jantung', name: 'HENTI_JANTUNG', score: 0, color: 'score-3' },
        ]},
    ];

    let assessments = [];

    // --- UI FUNCTIONS ---
    function renderTable() {
        const thead = $('#pewsTable thead');
        const tbody = $('#pewsTableBody');
        thead.empty();
        tbody.empty();

        let headerHtml = '<tr><th class="sticky-col" style="width: 250px;">Parameter</th>';
        if (assessments.length === 0) {
            headerHtml += '<th class="text-center">Pemeriksaan 1</th>';
        } else {
            assessments.forEach((ass, index) => {
                headerHtml += `<th class="text-center">Pemeriksaan ${index + 1} <button class="btn btn-xs btn-danger btn-remove-assessment" data-counter="${ass.COUNTER}" title="Hapus Pemeriksaan"><i class="fas fa-trash-alt"></i></button></th>`;
            });
        }
        headerHtml += '</tr>';
        thead.html(headerHtml);

        parameters.forEach(param => {
            let rowHtml = `<tr><td class="sticky-col ${param.options ? '' : 'font-weight-bold'}">${param.group}</td>`;

            const renderCell = (assessment, index) => {
                const counter = assessment ? assessment.COUNTER : 'new_0';
                let cellContent = '';

                if (param.type === 'date') {
                    const val = assessment ? (assessment.TGL || '') : moment().format('YYYY-MM-DD');
                    cellContent = `<input type="date" class="form-control form-control-sm" data-counter="${counter}" data-name="TGL" value="${val}">`;
                } else if (param.type === 'time') {
                    const val = assessment ? (assessment.JAM || '') : moment().format('HH:mm');
                    cellContent = `<input type="time" class="form-control form-control-sm" data-counter="${counter}" data-name="JAM" value="${val}">`;
                } else if (param.type === 'text') {
                    const val = assessment ? (assessment.NAMA_PPA || config.currentUser) : config.currentUser;
                    cellContent = `<input type="text" class="form-control form-control-sm" data-counter="${counter}" data-name="NAMA_PPA" value="${val}">`;
                } else if (param.type === 'total') {
                    const val = assessment ? (assessment.TOTAL_SKOR || 0) : 0;
                    cellContent = `<div class="total-score-cell text-center" data-counter="${counter}" data-name="TOTAL_SKOR">${val}</div>`;
                } else if (param.type === 'conclusion') {
                    cellContent = `<div class="conclusion-cell text-center font-weight-bold" data-counter="${counter}" data-name="KESIMPULAN">-</div>`;
                } else if (param.options) {
                    cellContent = '<div class="btn-group-vertical btn-group-toggle w-100" data-toggle="buttons">';
                    param.options.forEach(opt => {
                        const isChecked = assessment ? (assessment[opt.name] == 1) : false;
                        const activeClass = isChecked ? 'active' : '';
                        const colorClass = opt.color || `score-${opt.score}`;
                        cellContent += `
                            <label class="btn btn-outline-secondary btn-sm ${activeClass} ${colorClass}">
                                <input type="radio" name="radio_${param.group.replace(/[^a-zA-Z0-9]/g, '')}_${counter}" class="pews-radio"
                                       data-counter="${counter}" data-name="${opt.name}" data-score="${opt.score}" ${isChecked ? 'checked' : ''}>
                                ${opt.label}
                            </label>`;
                    });
                    cellContent += '</div>';
                }
                return `<td>${cellContent}</td>`;
            };

            if (assessments.length === 0) {
                rowHtml += renderCell(null, 0);
            } else {
                assessments.forEach((ass, index) => {
                    rowHtml += renderCell(ass, index);
                });
            }
            rowHtml += '</tr>';
            tbody.append(rowHtml);
        });

        if (assessments.length === 0) {
            calculateScore('new_0');
        } else {
            assessments.forEach(ass => calculateScore(ass.COUNTER));
        }
    }

    function calculateScore(counter) {
        let totalScore = 0;
        $(`.pews-radio[data-counter="${counter}"]:checked`).each(function() {
            totalScore += parseInt($(this).data('score'));
        });

        const totalCell = $(`.total-score-cell[data-counter="${counter}"]`);
        totalCell.text(totalScore);

        const conclusionCell = $(`.conclusion-cell[data-counter="${counter}"]`);
        let conclusionText = '-';
        let conclusionClass = '';
        if ($(`.pews-radio[data-name="HENTI_JANTUNG"][data-counter="${counter}"]`).is(':checked')) {
            conclusionText = 'HENTI JANTUNG';
            conclusionClass = 'score-3';
        } else if (totalScore >= 7) {
            conclusionText = '≥7';
            conclusionClass = 'score-3';
        } else if (totalScore >= 5) {
            conclusionText = '5-6';
            conclusionClass = 'score-2';
        } else if (totalScore >= 3) {
            conclusionText = '3-4';
            conclusionClass = 'score-1';
        } else {
            conclusionText = '0-2';
            conclusionClass = 'score-0';
        }
        conclusionCell.text(conclusionText).removeClass('score-0 score-1 score-2 score-3').addClass(conclusionClass);
    }

    // --- DATA HANDLING ---
    function loadHistory() {
        $.get(config.urls.history, { nopendaftaran: config.noPendaftaran }, function(response) {
            if (response.status === 'success') {
                assessments = response.data;
                if (assessments.length === 0) {
                    addAssessment();
                } else {
                    renderTable();
                }
            } else {
                Swal.fire('Error', 'Gagal memuat riwayat PEWS.', 'error');
                addAssessment();
            }
        }).fail(() => {
            Swal.fire('Error', 'Gagal menghubungi server untuk memuat riwayat.', 'error');
            addAssessment();
        });
    }

    function addAssessment() {
        const newCounter = assessments.length > 0 ? Math.max(...assessments.map(a => a.COUNTER)) + 1 : 1;
        const newAssessment = { COUNTER: newCounter, isNew: true };
        
        parameters.forEach(param => {
            if (param.name === 'TGL') newAssessment[param.name] = moment().format('YYYY-MM-DD');
            else if (param.name === 'JAM') newAssessment[param.name] = moment().format('HH:mm');
            else if (param.name === 'NAMA_PPA') newAssessment[param.name] = config.currentUser;
            
            if (param.options) {
                param.options.forEach(opt => newAssessment[opt.name] = 0);
            }
        });
        assessments.push(newAssessment);
        renderTable();
    }

    function saveAll() {
        const assessmentsToSave = [];
        const counters = assessments.map(a => a.COUNTER);

        counters.forEach(counter => {
            const assessmentData = { COUNTER: counter };
            $(`[data-counter="${counter}"]`).each(function() {
                const el = $(this);
                const name = el.data('name');
                if (el.is('input[type="date"], input[type="time"], input[type="text"]')) {
                    assessmentData[name] = el.val();
                }
            });

            $(`.pews-radio[data-counter="${counter}"]`).each(function() {
                const el = $(this);
                assessmentData[el.data('name')] = el.is(':checked') ? 1 : 0;
            });

            assessmentsToSave.push(assessmentData);
        });

        const button = $('#btnSaveAllPews');
        button.prop('disabled', true).html('<i class="fas fa-spinner fa-spin mr-1"></i>Menyimpan...');

        // Log details before AJAX call for debugging
        console.log('Attempting to save PEWS data via AJAX POST.');
        console.log('URL for store:', config.urls.store);
        console.log('Method for store:', 'POST');
        console.log('Data being sent:', assessmentsToSave);
        $.ajax({
            url: config.urls.store,
            type: 'POST',
            data: {
                _token: "{{ csrf_token() }}",
                nopendaftaran: config.noPendaftaran,
                norm: config.norm,
                assessments: assessmentsToSave
            },
            success: function(response) {
                if (response.status === 'success') {
                    Swal.fire('Berhasil', response.message, 'success').then(() => {
                        loadHistory();
                    });
                } else {
                    Swal.fire('Gagal', response.message || 'Terjadi kesalahan saat menyimpan.', 'error');
                }
            },
            complete: function() {
                button.prop('disabled', false).html('<i class="fas fa-save mr-1"></i>Simpan Semua');
            }
        });
    }

    function removeAssessment(counter) {
        const assessment = assessments.find(a => a.COUNTER == counter);

        Swal.fire({
            title: 'Hapus Pemeriksaan Ini?',
            text: "Tindakan ini tidak dapat dibatalkan.",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Ya, Hapus!',
            cancelButtonText: 'Batal'
        }).then((result) => {
            if (result.isConfirmed) {
                if (assessment && assessment.isNew) {
                    assessments = assessments.filter(a => a.COUNTER != counter);
                    renderTable();
                    Swal.fire('Dibatalkan', 'Pemeriksaan baru telah dibatalkan.', 'info');
                } else {
                    $.ajax({
                        url: config.urls.destroy,
                        type: 'POST',
                        data: {
                            _token: "{{ csrf_token() }}",
                            nopendaftaran: config.noPendaftaran,
                            counter: counter
                        },
                        success: function(response) {
                            if (response.status === 'success') {
                                Swal.fire('Terhapus!', response.message, 'success').then(() => {
                                    loadHistory();
                                });
                            } else {
                                Swal.fire('Gagal', response.message, 'error');
                            }
                        },
                        error: function(xhr) {
                            Swal.fire('Error', xhr.responseJSON?.message || 'Gagal menghubungi server.', 'error');
                        }
                    });
                }
            }
        });
    }

    // --- EVENT LISTENERS ---
    $('#btnAddAssessmentPews').click(addAssessment);
    $('#btnSaveAllPews').click(saveAll);

    $(document).on('click', '.btn-group-toggle .btn', function(e) {
        const $label = $(this);
        if ($label.hasClass('active')) {
            e.preventDefault();
            $label.removeClass('active');
            $label.find('.pews-radio').prop('checked', false).trigger('change');
        }
    });

    $(document).on('change', '.pews-radio', function() {
        const counter = $(this).data('counter');
        calculateScore(counter);
    });

    $(document).on('click', '.btn-remove-assessment', function() {
        const counter = $(this).data('counter');
        removeAssessment(counter);
    });

    // --- INITIAL LOAD ---
    loadHistory();
});
</script>