CREATE TABLE SKRINSEPSIS (
    NOPENDAFTARAN char(17) PRIMARY KEY,
    USER_ENTRY VARCHAR(25),
    TGLJAM_ENTRY DATETIME,

    PENURUNANSADAR BIT,
    TAKIPNEU BIT,
    SISTOLIK BIT,

    KESIMPULAN VARCHAR(25),

    RTL VARCHAR(200)
);