<div class="card-body">
    {{-- Hidden fields for URLs and data --}}
    <input type="hidden" id="ews-nopendaftaran" value="{{ $noPendaftaran }}">
    <input type="hidden" id="ews-norm" value="{{ $norm }}">
    <input type="hidden" id="ews-user" value="{{ trim($user['username']) }}">
    <input type="hidden" id="ews-url-history" value="{{ route('rme.igd.form.ews.history') }}">
    <input type="hidden" id="ews-url-store" value="{{ route('rme.igd.form.ews.store') }}">
    <input type="hidden" id="ews-url-destroy" value="{{ route('rme.igd.form.ews.destroy') }}">

    <div class="card card-outline card-primary shadow-sm">
        <div class="card-header">
            <h3 class="card-title mt-1">Neonatal EWS (Early Warning Score)</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-success btn-sm" id="btnAddAssessmentEws">
                    <i class="fas fa-plus-circle mr-1"></i>Tambah Pemeriksaan
                </button>
                <button type="button" class="btn btn-primary btn-sm" id="btnSaveAllEws">
                    <i class="fas fa-save mr-1"></i>Simpan Semua
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive" id="ews-table-container">
                <table class="table table-bordered table-hover" id="ewsTable" style="min-width: 1000px;">
                    <thead class="thead-light text-center align-middle">
                        {{-- Header will be generated by JS --}}
                    </thead>
                    <tbody id="ewsTableBody">
                        <tr>
                            <td colspan="10" class="text-center p-5">
                                <i class="fas fa-spinner fa-spin fa-2x"></i>
                                <p class="mt-2">Memuat data...</p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="alert alert-info mt-3">
                <h5 class="alert-heading"><i class="fas fa-info-circle"></i> Petunjuk Skor:</h5>
                <ul class="mb-0 pl-4">
                    <li><strong>Hijau (Skor 0):</strong> Pasien stabil, observasi setiap 1 jam.</li>
                    <li><strong>Kuning (Skor 1):</strong> Jika ada 1 kriteria, observasi tiap 30 menit. Jika 2 atau lebih, lapor dokter jaga/DPJP.</li>
                    <li><strong>Merah (Skor ≥ 2):</strong> Panggil dokter jaga/code blue untuk tatalaksana emergensi, konsul DPJP.</li>
                    <li><strong>Biru (*):</strong> Panggil dokter jaga/code blue untuk tatalaksana emergensi, DPJP perlu hadir.</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<style>
    #ewsTable th, #ewsTable td {
        vertical-align: middle;
    }
    #ewsTable .sticky-col {
        position: sticky;
        left: 0;
        z-index: 2;
        background-color: #fff;
    }
    #ewsTable thead .sticky-col {
        z-index: 3;
    }
    .btn-outline-secondary.score-0.active { background-color: #28a745 !important; border-color: #28a745 !important; color: white !important; }
    .btn-outline-secondary.score-1.active { background-color: #ffc107 !important; border-color: #ffc107 !important; color: black !important; }
    .btn-outline-secondary.score-2.active { background-color: #dc3545 !important; border-color: #dc3545 !important; color: white !important; }
    .btn-outline-secondary.score-critical.active { background-color: #0d6efd !important; border-color: #0d6efd !important; color: white !important; }

    .total-score-cell {
        font-weight: bold;
        font-size: 1.2rem;
    }
</style>

<script>
$(document).ready(function() {
    // --- CONFIG & GLOBAL VARS ---
    const config = {
        noPendaftaran: $('#ews-nopendaftaran').val(),
        norm: $('#ews-norm').val(),
        currentUser: $('#ews-user').val(),
        urls: {
            history: $('#ews-url-history').val(),
            store: $('#ews-url-store').val(),
            destroy: $('#ews-url-destroy').val(),
        }
    };

    const parameters = [
        { group: 'Tanggal Pemeriksaan', name: 'TGL', type: 'date' },
        { group: 'Jam Pemeriksaan', name: 'JAM', type: 'time' },
        { group: 'Suhu (°C)', options: [
            { label: '≥ 37,6', name: 'SUHU_37', score: 2, color: 'score-2' },
            { label: '36,5-37,5', name: 'SUHU_36', score: 0, color: 'score-0' },
            { label: '35,1-36,4', name: 'SUHU_35', score: 1, color: 'score-1' },
            { label: '≤ 35', name: 'SUHU_30', score: 2, color: 'score-2' },
        ]},
        { group: 'Frekuensi Nafas (x/menit)', options: [
            { label: '≥ 81', name: 'FREKUENSI_NAFAS_81', score: 2, color: 'score-2' },
            { label: '61-80', name: 'FREKUENSI_NAFAS_61', score: 1, color: 'score-1' },
            { label: '40-60', name: 'FREKUENSI_NAFAS_40', score: 0, color: 'score-0' },
            { label: '26-39', name: 'FREKUENSI_NAFAS_26', score: 1, color: 'score-1' },
            { label: '≤ 25', name: 'FREKUENSI_NAFAS_25', score: 2, color: 'score-2' },
        ]},
        { group: 'Nadi (x/menit)', options: [
            { label: '≥ 181', name: 'NADI_181', score: 2, color: 'score-2' },
            { label: '161-180', name: 'NADI_161', score: 1, color: 'score-1' },
            { label: '100-160', name: 'NADI_100', score: 0, color: 'score-0' },
            { label: '60-100', name: 'NADI_60', score: 1, color: 'score-1' },
            { label: '≤ 59', name: 'NADI_59', score: 2, color: 'score-2' },
        ]},
        { group: 'Saturasi Oksigen (%)', options: [
            { label: '≥ 93', name: 'SATURASI_OKSIGEN_93', score: 0, color: 'score-0' },
            { label: '88-92', name: 'SATURASI_OKSIGEN_92', score: 1, color: 'score-1' },
            { label: '≤ 87', name: 'SATURASI_OKSIGEN_87', score: 2, color: 'score-2' },
        ]},
        { group: 'Kesadaran', options: [
            { label: 'Aktif', name: 'KESADARAN_AKTIF', score: 0, color: 'score-0' },
            { label: 'Gelisah', name: 'KESADARAN_GELISAH', score: 1, color: 'score-1' },
            { label: 'Letargis', name: 'KESADARAN_LETARGIS', score: 2, color: 'score-2' },
        ]},
        { group: 'Kondisi Kritis (*)', options: [
            { label: 'Merintih', name: 'MERINTIH', score: 0, color: 'score-critical' },
            { label: 'Kejang', name: 'KEJANG', score: 0, color: 'score-critical' },
            { label: 'Glukosa < 47 mg/dL', name: 'GLUKOSA', score: 0, color: 'score-critical' },
        ]},
        { group: 'Total Skor', name: 'TOTAL_SKOR', type: 'total' },
        { group: 'Nama Petugas PPA', name: 'NAMA_PPA', type: 'text' },
        { group: 'Kesimpulan', name: 'KESIMPULAN', type: 'conclusion' },
    ];

    let assessments = [];

    // --- UI FUNCTIONS ---
    function renderTable() {
        const thead = $('#ewsTable thead');
        const tbody = $('#ewsTableBody');
        thead.empty();
        tbody.empty();

        let headerHtml = '<tr><th class="sticky-col" style="width: 250px;">Parameter</th>';
        if (assessments.length === 0) {
            headerHtml += '<th class="text-center">Pemeriksaan 1</th>';
        } else {
            assessments.forEach((ass, index) => {
                headerHtml += `<th class="text-center">Pemeriksaan ${index + 1} <button class="btn btn-xs btn-danger btn-remove-assessment" data-counter="${ass.COUNTER}" title="Hapus Pemeriksaan"><i class="fas fa-trash-alt"></i></button></th>`;
            });
        }
        headerHtml += '</tr>';
        thead.html(headerHtml);

        parameters.forEach(param => {
            let rowHtml = `<tr><td class="sticky-col ${param.options ? '' : 'font-weight-bold'}">${param.group}</td>`;

            const renderCell = (assessment, index) => {
                const counter = assessment ? assessment.COUNTER : 'new_0';
                let cellContent = '';

                if (param.type === 'date') {
                    const val = assessment ? (assessment.TGL || '') : moment().format('YYYY-MM-DD');
                    cellContent = `<input type="date" class="form-control form-control-sm" data-counter="${counter}" data-name="TGL" value="${val}">`;
                } else if (param.type === 'time') {
                    const val = assessment ? (assessment.JAM || '') : moment().format('HH:mm');
                    cellContent = `<input type="time" class="form-control form-control-sm" data-counter="${counter}" data-name="JAM" value="${val}">`;
                } else if (param.type === 'text') {
                    const val = assessment ? (assessment.NAMA_PPA || config.currentUser) : config.currentUser;
                    cellContent = `<input type="text" class="form-control form-control-sm" data-counter="${counter}" data-name="NAMA_PPA" value="${val}">`;
                } else if (param.type === 'total') {
                    const val = assessment ? (assessment.TOTAL_SKOR || 0) : 0;
                    cellContent = `<div class="total-score-cell text-center" data-counter="${counter}" data-name="TOTAL_SKOR">${val}</div>`;
                } else if (param.type === 'conclusion') {
                    cellContent = `<div class="conclusion-cell text-center font-weight-bold" data-counter="${counter}" data-name="KESIMPULAN">-</div>`;
                } else if (param.options) {
                    cellContent = '<div class="btn-group-vertical btn-group-toggle w-100" data-toggle="buttons">';
                    param.options.forEach(opt => {
                        const isChecked = assessment ? (assessment[opt.name] == 1) : false;
                        const activeClass = isChecked ? 'active' : '';
                        const colorClass = opt.color || `score-${opt.score}`;
                        cellContent += `
                            <label class="btn btn-outline-secondary btn-sm ${activeClass} ${colorClass}">
                                <input type="radio" name="radio_${param.group.replace(/[^a-zA-Z0-9]/g, '')}_${counter}" class="ews-radio"
                                       data-counter="${counter}" data-name="${opt.name}" data-score="${opt.score}" ${isChecked ? 'checked' : ''}>
                                ${opt.label}
                            </label>`;
                    });
                    cellContent += '</div>';
                }
                return `<td>${cellContent}</td>`;
            };

            if (assessments.length === 0) {
                rowHtml += renderCell(null, 0);
            } else {
                assessments.forEach((ass, index) => {
                    rowHtml += renderCell(ass, index);
                });
            }
            rowHtml += '</tr>';
            tbody.append(rowHtml);
        });

        if (assessments.length === 0) {
            calculateScore('new_0');
        } else {
            assessments.forEach(ass => calculateScore(ass.COUNTER));
        }
    }

    function calculateScore(counter) {
        let totalScore = 0;
        let isCritical = false;

        $(`.ews-radio[data-counter="${counter}"]:checked`).each(function() {
            const name = $(this).data('name');
            if (['MERINTIH', 'KEJANG', 'GLUKOSA'].includes(name)) {
                isCritical = true;
            }
        });

        // Disable/enable scoring radios based on critical status
        const scoringRadioNames = [
            'SUHU_37', 'SUHU_36', 'SUHU_35', 'SUHU_30',
            'FREKUENSI_NAFAS_81', 'FREKUENSI_NAFAS_61', 'FREKUENSI_NAFAS_40', 'FREKUENSI_NAFAS_26', 'FREKUENSI_NAFAS_25',
            'NADI_181', 'NADI_161', 'NADI_100', 'NADI_60', 'NADI_59',
            'SATURASI_OKSIGEN_93', 'SATURASI_OKSIGEN_92', 'SATURASI_OKSIGEN_87',
            'KESADARAN_AKTIF', 'KESADARAN_GELISAH', 'KESADARAN_LETARGIS'
        ];

        scoringRadioNames.forEach(name => {
            const radio = $(`.ews-radio[data-name="${name}"][data-counter="${counter}"]`);
            if (isCritical) {
                radio.prop('disabled', true).prop('checked', false).closest('label').removeClass('active');
            } else {
                radio.prop('disabled', false);
            }
        });

        if (isCritical) {
            // Show alert if not already shown for this critical event
            if (!$(`.ews-radio[data-name="MERINTIH"][data-counter="${counter}"]`).data('alerted') && $(`.ews-radio[data-name="MERINTIH"][data-counter="${counter}"]`).is(':checked') ||
                !$(`.ews-radio[data-name="KEJANG"][data-counter="${counter}"]`).data('alerted') && $(`.ews-radio[data-name="KEJANG"][data-counter="${counter}"]`).is(':checked') ||
                !$(`.ews-radio[data-name="GLUKOSA"][data-counter="${counter}"]`).data('alerted') && $(`.ews-radio[data-name="GLUKOSA"][data-counter="${counter}"]`).is(':checked')) {
                
                Swal.fire({
                    title: 'Pasien Kritis!',
                    html: '<div class="alert alert-danger"><strong>Pasien harus segera ditangani!</strong><br>Segera panggil dokter untuk memeriksa pasien.</div>',
                    icon: 'warning',
                    confirmButtonText: 'Mengerti',
                });
                $(`.ews-radio[data-counter="${counter}"]:checked`).data('alerted', true);
            }
        }

        totalScore = 0; // Recalculate score
        $(`.ews-radio[data-counter="${counter}"]:checked`).each(function() {
            const score = parseInt($(this).data('score'));
            const name = $(this).data('name');
            if (['MERINTIH', 'KEJANG', 'GLUKOSA'].includes(name)) {
                isCritical = true;
            } else {
                totalScore += score;
            }
        });

        const totalCell = $(`.total-score-cell[data-counter="${counter}"]`);
        totalCell.text(isCritical ? '0' : totalScore); // Score is 0 if critical

        const conclusionCell = $(`.conclusion-cell[data-counter="${counter}"]`);
        let conclusionText = '-';
        let conclusionClass = '';

        if (isCritical) {
            conclusionText = 'Biru (*)';
            conclusionClass = 'score-critical';
        } else if (totalScore >= 2) {
            conclusionText = 'Merah';
            conclusionClass = 'score-2';
        } else if (totalScore === 1) {
            conclusionText = 'Kuning';
            conclusionClass = 'score-1';
        } else {
            conclusionText = 'Hijau';
            conclusionClass = 'score-0';
        }
        conclusionCell.text(conclusionText).removeClass('score-0 score-1 score-2 score-critical').addClass(conclusionClass);
    }

    // --- DATA HANDLING ---
    function loadHistory() {
        $.get(config.urls.history, { nopendaftaran: config.noPendaftaran }, function(response) {
            if (response.status === 'success') {
                assessments = response.data;
                if (assessments.length === 0) {
                    addAssessment();
                } else {
                    renderTable();
                }
            } else {
                Swal.fire('Error', 'Gagal memuat riwayat EWS.', 'error');
                addAssessment();
            }
        }).fail(() => {
            Swal.fire('Error', 'Gagal menghubungi server untuk memuat riwayat.', 'error');
            addAssessment();
        });
    }

    function addAssessment() {
        const newCounter = assessments.length > 0 ? Math.max(...assessments.map(a => a.COUNTER)) + 1 : 1;
        const newAssessment = { COUNTER: newCounter, isNew: true };
        
        parameters.forEach(param => {
            if (param.name === 'TGL') newAssessment[param.name] = moment().format('YYYY-MM-DD');
            else if (param.name === 'JAM') newAssessment[param.name] = moment().format('HH:mm');
            else if (param.name === 'NAMA_PPA') newAssessment[param.name] = config.currentUser;
            
            if (param.options) {
                param.options.forEach(opt => newAssessment[opt.name] = 0);
            }
        });
        assessments.push(newAssessment);
        renderTable();
    }

    function saveAll() {
        const assessmentsToSave = [];
        const counters = assessments.map(a => a.COUNTER);

        counters.forEach(counter => {
            const assessmentData = { COUNTER: counter };
            $(`[data-counter="${counter}"]`).each(function() {
                const el = $(this);
                const name = el.data('name');
                if (el.is('input[type="date"], input[type="time"], input[type="text"]')) {
                    assessmentData[name] = el.val();
                }
            });

            $(`.ews-radio[data-counter="${counter}"]`).each(function() {
                const el = $(this);
                assessmentData[el.data('name')] = el.is(':checked') ? 1 : 0;
            });

            assessmentsToSave.push(assessmentData);
        });

        const button = $('#btnSaveAllEws');
        button.prop('disabled', true).html('<i class="fas fa-spinner fa-spin mr-1"></i>Menyimpan...');

        $.ajax({
            url: config.urls.store,
            type: 'POST',
            data: {
                _token: "{{ csrf_token() }}",
                nopendaftaran: config.noPendaftaran,
                norm: config.norm,
                assessments: assessmentsToSave
            },
            success: function(response) {
                if (response.status === 'success') {
                    Swal.fire('Berhasil', response.message, 'success').then(() => {
                        loadHistory();
                    });
                } else {
                    Swal.fire('Gagal', response.message || 'Terjadi kesalahan saat menyimpan.', 'error');
                }
            },
            complete: function() {
                button.prop('disabled', false).html('<i class="fas fa-save mr-1"></i>Simpan Semua');
            }
        });
    }

    function removeAssessment(counter) {
        const assessment = assessments.find(a => a.COUNTER == counter);

        Swal.fire({
            title: 'Hapus Pemeriksaan Ini?',
            text: "Tindakan ini tidak dapat dibatalkan.",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Ya, Hapus!',
            cancelButtonText: 'Batal'
        }).then((result) => {
            if (result.isConfirmed) {
                if (assessment && assessment.isNew) {
                    assessments = assessments.filter(a => a.COUNTER != counter);
                    renderTable();
                    Swal.fire('Dibatalkan', 'Pemeriksaan baru telah dibatalkan.', 'info');
                } else {
                    $.ajax({
                        url: config.urls.destroy,
                        type: 'POST',
                        data: {
                            _token: "{{ csrf_token() }}",
                            nopendaftaran: config.noPendaftaran,
                            counter: counter
                        },
                        success: function(response) {
                            if (response.status === 'success') {
                                Swal.fire('Terhapus!', response.message, 'success').then(() => {
                                    loadHistory();
                                });
                            } else {
                                Swal.fire('Gagal', response.message, 'error');
                            }
                        },
                        error: function(xhr) {
                            Swal.fire('Error', xhr.responseJSON?.message || 'Gagal menghubungi server.', 'error');
                        }
                    });
                }
            }
        });
    }

    // --- EVENT LISTENERS ---
    $('#btnAddAssessmentEws').click(addAssessment);
    $('#btnSaveAllEws').click(saveAll);

    $(document).on('click', '.btn-group-toggle .btn', function(e) {
        const $label = $(this);
        if ($label.hasClass('active')) {
            e.preventDefault();
            $label.removeClass('active');
            $label.find('.ews-radio').prop('checked', false).trigger('change');
        }
    });

    $(document).on('change', '.ews-radio', function() {
        const counter = $(this).data('counter');
        calculateScore(counter);
    });

    $(document).on('click', '.btn-remove-assessment', function() {
        const counter = $(this).data('counter');
        removeAssessment(counter);
    });

    // --- INITIAL LOAD ---
    loadHistory();
});
</script>