CREATE TABLE RM55 (
    NOPENDAFTARAN char(17) PRIMARY KEY,
    USER_ENTRY VARCHAR(25),
    TGLJAM_ENTRY DATETIME,

    HARI VARCHAR(25),
    TANGGAL DATETIME,
    BULAN VARCHAR2(25),
    TAHU VARCHAR(10),

    
);