CREATE TABLE RM80 (
    NOPENDAFTARAN char(17) PRIMARY KEY,
    USER_ENTRY VARCHAR(25),
    TGLJAM_ENTRY DATETIME,

    HARI VARCHAR(25),
    TANGGAL DATETIME,
    BULAN VARCHAR(25),
    TAHUN VARCHAR(10),
    NM_BERTANDA VARCHAR(100),
    JAB_BERTANDA VARCHAR(100),

    NM_PIHAK VARCHAR(100),
    JAB_PIHAK VARCHAR(100),

    NM_BAYI VARCHAR(100),
    TGLLAHIR_BAYI DATETIME,
    BB_BATI VARCHAR(25),
    SURAT_KETLAHIR VARCHAR(100),
    KEADAAN VARCHAR(200),
    JAM CHAR(8),
    PANJANG_LAHIR VARCHAR(25),

    TTD_PENERIMA IMAGE,
    TTD_MENYERAHKAN IMAGE
);